// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUaMTfQF-6gfMh2qBNMpiElKQGa1Jp9A0',
    appId: '1:595686443810:web:b457e25af9b6df2632f37b',
    messagingSenderId: '595686443810',
    projectId: 'digitalfarmerhub',
    authDomain: 'digitalfarmerhub.firebaseapp.com',
    storageBucket: 'digitalfarmerhub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxVC3SOpODs-87oFyIbn-a2AP24kM5IEc',
    appId: '1:595686443810:android:2f7af05af191814c32f37b',
    messagingSenderId: '595686443810',
    projectId: 'digitalfarmerhub',
    storageBucket: 'digitalfarmerhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpG17CHU0b2jh2Qr_0AKinUqnGtkoTq_E',
    appId: '1:595686443810:ios:a6c6103b688392b232f37b',
    messagingSenderId: '595686443810',
    projectId: 'digitalfarmerhub',
    storageBucket: 'digitalfarmerhub.appspot.com',
    iosBundleId: 'com.auribises.digitalFarmerHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpG17CHU0b2jh2Qr_0AKinUqnGtkoTq_E',
    appId: '1:595686443810:ios:a6c6103b688392b232f37b',
    messagingSenderId: '595686443810',
    projectId: 'digitalfarmerhub',
    storageBucket: 'digitalfarmerhub.appspot.com',
    iosBundleId: 'com.auribises.digitalFarmerHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUaMTfQF-6gfMh2qBNMpiElKQGa1Jp9A0',
    appId: '1:595686443810:web:5e4a9bd0e4bcdee232f37b',
    messagingSenderId: '595686443810',
    projectId: 'digitalfarmerhub',
    authDomain: 'digitalfarmerhub.firebaseapp.com',
    storageBucket: 'digitalfarmerhub.appspot.com',
  );
}
